signals:
  buy_signal:
    function: "lambda current_price, predicted_high, buy_threshold: current_price < predicted_high * (1 + buy_threshold)"
    params:
      buy_threshold: 0.0  # Set a 2% buffer to reduce frequency of buy signals

  sell_signal:
    function: "lambda current_price, buy_price, sell_threshold: current_price > buy_price * (1 + sell_threshold)"
    params:
      sell_threshold: 0.0  # Set a 3% buffer for sell signals to prevent immediate selling

  stop_loss_signal:
    function: "lambda current_price, buy_price, stop_loss_threshold: current_price <= buy_price * (1 - stop_loss_threshold)"
    params:
      stop_loss_threshold: 0.01  # 1% stop-loss threshold

strategies:
  trading_strategy:
    description: "Strategy combining buy, sell, and stop-loss signals."
    buy_signal: "buy_signal"
    sell_signal: "sell_signal"
    stop_loss_signal: "stop_loss_signal"
    params:
      initial_cash: 100000  
      position_size_factor: 0.1  
      max_holding_time: 5   # Max holding time remains the same
      min_holding_period: 3  # Minimum holding period in minutes (or adjust as needed)
