trading_strategy:
  initial_cash: 100000          # Starting cash
  position_size_factor: 0.1     # Allocate 10% of capital to stock
  buy_threshold: 0.002         # Adjusted buy threshold to be more lenient

  buy_strategy:
    condition:                  # Buy condition
      description: "Predicted high is 0.2% higher than current price and no current position"
      expression: "position == 0 and predicted_high > current_price * (1 + buy_threshold)"
    
  sell_strategy:
    condition:                  # Sell condition
      description: "Current price reaches or exceeds predicted high"
      expression: "position > 0 and current_price >= predicted_high"
      
  exit_strategy:
    condition:                  # Exit condition (can be customized)
      description: "Reset position after selling"
      expression: "position == 0"

 